/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
import java.util.ArrayList;
import java.util.List;

public class FormPrincipal extends javax.swing.JFrame {
    
    //linha para criar a lista central de reservas
    public static List<Reserva> listaDeReservas = new ArrayList<>();
    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
        
        // Adicione esta linha para desabilitar o botão 'X'
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rtCadas = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        rtFazCad = new javax.swing.JMenuItem();
        rtSai = new javax.swing.JMenuItem();
        rtRelat = new javax.swing.JMenu();
        rtListRelat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulário Principal");

        jMenu1.setText("Cadastro");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        rtFazCad.setText("Fazer Cadastro");
        rtFazCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtFazCadActionPerformed(evt);
            }
        });
        jMenu1.add(rtFazCad);

        rtSai.setText("Sair");
        rtSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtSaiActionPerformed(evt);
            }
        });
        jMenu1.add(rtSai);

        rtCadas.add(jMenu1);

        rtRelat.setText("Relatório");

        rtListRelat.setText("Listar Relatório");
        rtListRelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtListRelatActionPerformed(evt);
            }
        });
        rtRelat.add(rtListRelat);

        rtCadas.add(rtRelat);

        setJMenuBar(rtCadas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//bug
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void rtSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtSaiActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_rtSaiActionPerformed

    private void rtListRelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtListRelatActionPerformed
        // TODO add your handling code here:
        new FormsRelatorio().setVisible(true);
    }//GEN-LAST:event_rtListRelatActionPerformed

    private void rtFazCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtFazCadActionPerformed
        // TODO add your handling code here:
        new FormReserva().setVisible(true);
    }//GEN-LAST:event_rtFazCadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar rtCadas;
    private javax.swing.JMenuItem rtFazCad;
    private javax.swing.JMenuItem rtListRelat;
    private javax.swing.JMenu rtRelat;
    private javax.swing.JMenuItem rtSai;
    // End of variables declaration//GEN-END:variables
}
