/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class FormsRelatorio extends javax.swing.JFrame {
    
    /**
     * Creates new form FormsRelatorio
     */
    public FormsRelatorio() {
        initComponents();
        
         //Linha para que as células não sejam editáveis com um clique
        jTable1.setDefaultEditor(Object.class, null);
        
        //linha para desabilitar o botão 'X'
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        carregarTabela();
    }
    
    //Função para atualizar a tabela
    public void carregarTabela() {
        // 1. Obtém o modelo da tabela
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();

        // 2. Limpa as linhas existentes para evitar duplicatas
        model.setRowCount(0);

        // 3. Itera sobre a lista de reservas do FormPrincipal
        for (Reserva reserva : FormPrincipal.listaDeReservas) {
            // 4. Adiciona uma nova linha para cada reserva na tabela
            model.addRow(new Object[]{
                reserva.getMorador().getNome(),
                reserva.getMorador().getApartamento(),
                reserva.getData(),
                reserva.getEspacoLazer().getClass().getSimpleName() // Pega o nome da classe do espaço (Piscina, etc.)
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExcl = new javax.swing.JButton();
        btAlter = new javax.swing.JButton();
        btSai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btExcl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btExcl.setText("Excluir");
        btExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclActionPerformed(evt);
            }
        });

        btAlter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAlter.setText("Alterar");
        btAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterActionPerformed(evt);
            }
        });

        btSai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSai.setText("Sair");
        btSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Apartamento", "Data de Reserva", "Espaço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btExcl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btAlter)
                .addGap(58, 58, 58)
                .addComponent(btSai)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcl)
                    .addComponent(btAlter)
                    .addComponent(btSai))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 85, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclActionPerformed
    // 1. Pega o índice da linha que o usuário selecionou na tabela
    int selectedRow = jTable1.getSelectedRow();

    // 2. Verifica se o usuário realmente selecionou uma linha (o índice será -1 se nada for selecionado)
    if (selectedRow >= 0) {
        // 3. Pede uma confirmação ao usuário antes de excluir permanentemente
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja excluir esta reserva permanentemente?",
                "Confirmar Exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION);

        // 4. Se o usuário clicar em "Sim" (YES_OPTION)
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            // 5. REMOVE a reserva da lista de dados principal usando o índice da linha selecionada.
            // Esta é a etapa que faltava e que torna a exclusão definitiva.
            FormPrincipal.listaDeReservas.remove(selectedRow);

            // 6. Atualiza a tabela para refletir a remoção do item da lista.
            // Chamar carregarTabela() é uma forma simples e segura de garantir que a
            // tabela e a lista de dados estejam perfeitamente sincronizadas.
            carregarTabela();

            javax.swing.JOptionPane.showMessageDialog(this, "Reserva excluída com sucesso!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    } else {
        // 7. Se nenhuma linha foi selecionada, avisa o usuário.
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma reserva na tabela para excluir.", "Nenhuma seleção", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btExclActionPerformed

    private void btAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterActionPerformed
    
    int selectedRow = jTable1.getSelectedRow();

    // Verifica se uma linha foi realmente selecionada
    if (selectedRow >= 0) {
        // Pega a reserva correspondente da nossa lista principal
        Reserva reservaParaAlterar = FormPrincipal.listaDeReservas.get(selectedRow);

        // Abre o FormReserva em modo de edição, passando a reserva,
        // seu índice na lista e a referência a esta janela de relatório
        FormReserva formEdicao = new FormReserva(reservaParaAlterar, selectedRow, this);
        formEdicao.setVisible(true);

    } else {
        // Caso o usuário não tenha selecionado nada, exibe um aviso
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma reserva na tabela para alterar.", "Nenhuma seleção", javax.swing.JOptionPane.WARNING_MESSAGE);
    }
    
    }//GEN-LAST:event_btAlterActionPerformed

    private void btSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormsRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlter;
    private javax.swing.JButton btExcl;
    private javax.swing.JButton btSai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
