// Higor Silva Fernandes
// RA: 2313898

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Aluno
 */
public class FormsRelatorio extends javax.swing.JFrame {
    
    private static FormsRelatorio instancia;
    
    private FormsRelatorio() { // Construtor é PRIVADO
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jTable1.setDefaultEditor(Object.class, null);
    }
    
    //MÉTODO SINGLETON
    public static FormsRelatorio getInstancia() {
        if (instancia == null) {
            instancia = new FormsRelatorio();
        }
        return instancia;
    }
    
    //Função para atualizar a tabela
    public void carregarTabela() {
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        // Busca os dados diretamente da classe BDReserva
        for (Reserva reserva : BDReserva.getInstancia().getReservas()) {
            model.addRow(new Object[]{
                reserva.getMorador().getNome(),
                reserva.getMorador().getApartamento(),
                reserva.getData(),
                reserva.getEspacoLazer().getClass().getSimpleName()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btExcl = new javax.swing.JButton();
        btAlter = new javax.swing.JButton();
        btSai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btExcl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btExcl.setText("Excluir");
        btExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExclActionPerformed(evt);
            }
        });

        btAlter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btAlter.setText("Alterar");
        btAlter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterActionPerformed(evt);
            }
        });

        btSai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSai.setText("Sair");
        btSai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Apartamento", "Data de Reserva", "Espaço"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btExcl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btAlter)
                .addGap(58, 58, 58)
                .addComponent(btSai)
                .addGap(35, 35, 35))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcl)
                    .addComponent(btAlter)
                    .addComponent(btSai))
                .addGap(46, 46, 46))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 85, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExclActionPerformed
    int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            int confirmacao = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Tem certeza que deseja excluir esta reserva?", "Confirmar Exclusão",
                    javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
                // Exclui a reserva usando o método da classe BDReserva
                BDReserva.getInstancia().deleteReserva(selectedRow);
                carregarTabela(); // Atualiza a tabela
                
                javax.swing.JOptionPane.showMessageDialog(this, "Cadastro excluido com sucesso!!", "Sucesso", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma reserva para excluir.", "Nenhuma seleção", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btExclActionPerformed

    private void btAlterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterActionPerformed
    
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            // Pega a reserva do nosso "banco de dados"
            Reserva reservaParaAlterar = BDReserva.getInstancia().getReservaByIndex(selectedRow);

            // Abre o FormReserva em modo de edição.
            // A tela FormReserva também será um Singleton, então não usamos "new"
            FormReserva.getInstancia().prepararParaAlterar(reservaParaAlterar, selectedRow);
            FormReserva.getInstancia().setVisible(true);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma reserva para alterar.", "Nenhuma seleção", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    
    }//GEN-LAST:event_btAlterActionPerformed

    private void btSaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaiActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btSaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormsRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormsRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlter;
    private javax.swing.JButton btExcl;
    private javax.swing.JButton btSai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
